#!/usr/bin/env bash
set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────────
# PII Audit: GitHub Remote 기준 전수검사
# 로컬 git이 아니라 GitHub API에서 실제 파일 내용을 받아 검사.
# "남들이 보는 것" 기준.
# ──────────────────────────────────────────────────────────────────────────────

REPO="${1:-Ramsbaby/jarvis}"
BRANCH="${2:-main}"
REPORT_DIR="$HOME/.jarvis/reports"
REPORT="$REPORT_DIR/pii-audit-$(date +%Y%m%d_%H%M%S).md"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

mkdir -p "$REPORT_DIR"

echo "🔍 PII 전수검사 시작: $REPO ($BRANCH)"
echo "   대상: GitHub Remote (API 기반)"
echo ""

# ── 1. PII 패턴 정의 ────────────────────────────────────────────────────────
# 본인을 특정할 수 있는 모든 패턴 (넓은 범위)
PII_PATTERNS=(
  # 이름/이메일/연락처
  "Owner"
  "Owner"
  "owner-id"
  "010-[0-9]{4}-[0-9]{4}"

  # 전 직장 (경력 특정)
  "Company-A"
  "Company-A"
  "Company-B"
  "Company-B"

  # 면접/이직 대상 (구직 활동 특정)
  "Company-C"
  "company-c"

  # 부업 플랫폼 (수입원 특정)
  "[Pp]reply"
  "tutoring"

  # 가족/지인 이름
  "family-member"
  "jarvis-family"
  "FAMILY_"
  "isFamily"
  "familyOnly"

  # 군복무/학력 (신상 특정)
  "군복무"
  "1993년생"

  # Discord 사용자 ID (계정 특정)
  "1470007121440673933"
  "1468386844621144065"

  # filter-repo 잔해
  "tutoring-platform"
  "istutoring"
  "TUTORING_PATTERN"
  "BAD_TUTORING"
  "istutoringQuery"
)

# ── 2. GitHub API로 파일 목록 + 내용 검사 ────────────────────────────────────
echo "📥 파일 목록 수집 중..."
gh api "repos/$REPO/git/trees/$BRANCH?recursive=1" \
  --jq '.tree[] | select(.type=="blob") | .path' > "$tmp/files.txt"

TOTAL=$(wc -l < "$tmp/files.txt" | tr -d ' ')
echo "   총 $TOTAL 파일"
echo ""

# 바이너리/이미지 제외
grep -vE '\.(png|jpg|jpeg|gif|ico|woff2?|ttf|eot|svg|lock|min\.js|min\.css)$' \
  "$tmp/files.txt" | grep -v 'node_modules/' > "$tmp/text-files.txt" || true

TEXT_TOTAL=$(wc -l < "$tmp/text-files.txt" | tr -d ' ')
echo "   텍스트 파일: $TEXT_TOTAL"

FOUND_COUNT=0
FOUND_FILES=()
FOUND_DETAILS=()

echo "🔎 PII 패턴 검사 중..."
while IFS= read -r filepath; do
  # GitHub API로 파일 내용 가져오기 (base64 디코딩)
  content=$(gh api "repos/$REPO/contents/$filepath?ref=$BRANCH" --jq '.content' 2>/dev/null | base64 -d 2>/dev/null || true)

  if [[ -z "$content" ]]; then
    continue
  fi

  for pattern in "${PII_PATTERNS[@]}"; do
    matches=$(echo "$content" | grep -nE "$pattern" 2>/dev/null || true)
    if [[ -n "$matches" ]]; then
      FOUND_COUNT=$((FOUND_COUNT + 1))
      FOUND_FILES+=("$filepath")
      while IFS= read -r match_line; do
        FOUND_DETAILS+=("[$filepath] pattern=\"$pattern\" → $match_line")
      done <<< "$matches"
    fi
  done
done < "$tmp/text-files.txt"

# ── 3. git history 검사 (커밋 메시지 + diff) ────────────────────────────────
echo ""
echo "📜 git history 검사 중 (최근 100 커밋)..."

HISTORY_HITS=0
HISTORY_DETAILS=()

commits=$(gh api "repos/$REPO/commits?sha=$BRANCH&per_page=100" --jq '.[].sha' 2>/dev/null || true)

for sha in $commits; do
  msg=$(gh api "repos/$REPO/commits/$sha" --jq '.commit.message' 2>/dev/null || true)
  for pattern in "${PII_PATTERNS[@]}"; do
    if echo "$msg" | grep -qE "$pattern" 2>/dev/null; then
      HISTORY_HITS=$((HISTORY_HITS + 1))
      short_sha="${sha:0:7}"
      HISTORY_DETAILS+=("[commit $short_sha] pattern=\"$pattern\" in message")
    fi
  done
done

# ── 4. 리포트 생성 ──────────────────────────────────────────────────────────
{
  echo "# PII Audit Report"
  echo ""
  echo "- **대상**: \`$REPO\` / \`$BRANCH\`"
  echo "- **검사 시각**: $(date '+%Y-%m-%d %H:%M:%S KST')"
  echo "- **검사 방식**: GitHub API (remote 기준, 로컬 아님)"
  echo "- **총 파일**: $TOTAL (텍스트: $TEXT_TOTAL)"
  echo "- **PII 패턴**: ${#PII_PATTERNS[@]}개"
  echo ""

  if [[ ${#FOUND_DETAILS[@]} -eq 0 ]] && [[ $HISTORY_HITS -eq 0 ]]; then
    echo "## ✅ 결과: PII 0건 발견"
    echo ""
    echo "모든 파일과 최근 100개 커밋 메시지에서 PII 패턴이 발견되지 않았습니다."
  else
    echo "## ❌ 결과: PII 발견"
    echo ""

    if [[ ${#FOUND_DETAILS[@]} -gt 0 ]]; then
      echo "### 파일 내용 (${#FOUND_DETAILS[@]}건)"
      echo ""
      echo '```'
      for detail in "${FOUND_DETAILS[@]}"; do
        echo "$detail"
      done
      echo '```'
      echo ""
    fi

    if [[ $HISTORY_HITS -gt 0 ]]; then
      echo "### 커밋 메시지 (${HISTORY_HITS}건)"
      echo ""
      echo '```'
      for detail in "${HISTORY_DETAILS[@]}"; do
        echo "$detail"
      done
      echo '```'
    fi
  fi

  echo ""
  echo "---"
  echo "*Generated by pii-audit-remote.sh*"
} > "$REPORT"

echo ""
echo "════════════════════════════════════════════"
if [[ ${#FOUND_DETAILS[@]} -eq 0 ]] && [[ $HISTORY_HITS -eq 0 ]]; then
  echo "✅ PII 0건 — CLEAN"
else
  echo "❌ PII 발견: 파일 ${#FOUND_DETAILS[@]}건, 커밋 ${HISTORY_HITS}건"
fi
echo "════════════════════════════════════════════"
echo ""
echo "📄 리포트: $REPORT"
